# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import app.key_estimator.keyfinder_pb2 as keyfinder__pb2


class KeyFinderStub(object):
    """The service that defines the RPC method
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetKey = channel.unary_unary(
                '/keyfinder.KeyFinder/GetKey',
                request_serializer=keyfinder__pb2.KeyRequest.SerializeToString,
                response_deserializer=keyfinder__pb2.KeyResponse.FromString,
                )


class KeyFinderServicer(object):
    """The service that defines the RPC method
    """

    def GetKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyFinderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKey,
                    request_deserializer=keyfinder__pb2.KeyRequest.FromString,
                    response_serializer=keyfinder__pb2.KeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'keyfinder.KeyFinder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KeyFinder(object):
    """The service that defines the RPC method
    """

    @staticmethod
    def GetKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/keyfinder.KeyFinder/GetKey',
            keyfinder__pb2.KeyRequest.SerializeToString,
            keyfinder__pb2.KeyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
