# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keyfinder.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fkeyfinder.proto\x12\tkeyfinder\"D\n\nKeyRequest\x12\x10\n\x08pcm_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x63hannels\x18\x02 \x01(\x03\x12\x12\n\nframe_rate\x18\x03 \x01(\x03\"\x1a\n\x0bKeyResponse\x12\x0b\n\x03key\x18\x01 \x01(\t2D\n\tKeyFinder\x12\x37\n\x06GetKey\x12\x15.keyfinder.KeyRequest\x1a\x16.keyfinder.KeyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'keyfinder_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_KEYREQUEST']._serialized_start=30
  _globals['_KEYREQUEST']._serialized_end=98
  _globals['_KEYRESPONSE']._serialized_start=100
  _globals['_KEYRESPONSE']._serialized_end=126
  _globals['_KEYFINDER']._serialized_start=128
  _globals['_KEYFINDER']._serialized_end=196
# @@protoc_insertion_point(module_scope)
